### ISSUE TITLE
App freezes after a while when number of topics are more

### ISSUE THREAD

**Issue by Akhilesh002** [shamblett/mqtt5_client#10]
app freeze when the number of subscriptions are more. Pasted last trail logs here

`I/flutter ( 3602): 2021-02-08 19:21:33.752252 -- MqttServerConnection::_onData - message available event fired
I/flutter ( 3602): 2021-02-08 19:21:33.752355 -- MqttServerConnection::_onData - Message Received Ended <<< 
I/flutter ( 3602): 2021-02-08 19:21:33.753225 -- MqttConnectionHandlerBase::messageAvailable - message type is MqttMessageType.publish
I/flutter ( 3602): 2021-02-08 19:21:33.754938 -- MqttPublishingManager::handlePublish - entered
I/flutter ( 3602): 2021-02-08 19:21:33.759217 -- MqttConnectionHandlerBase::sendMessage - sending message started >>> -> MQTTMessage of type MqttMessageType.publishReceived
I/flutter ( 3602): MessageType = MqttMessageType.publishReceived Duplicate = false Retain = false Qos = atMostOnce Size = 0
I/flutter ( 3602): Message Identifier = 1
I/flutter ( 3602): Reason Code = success
I/flutter ( 3602): Properties = No properties set
I/flutter ( 3602): 
I/flutter ( 3602): 2021-02-08 19:21:33.760230 -- MqttConnectionHandlerBase::sendMessage - sending message ended >>>
I/flutter ( 3602): 2021-02-08 19:21:33.764121 -- MqttServerConnection::_onData - Message Received Started <<< 
I/flutter ( 3602): 2021-02-08 19:21:33.764245 -- MqttServerConnection::_ondata - adding incoming data, data length is 1168, message stream length is 0, message stream position is 0
`

**Comment by shamblett** [comment]
Not sure what you mean by 'number of topics are more'. More than what, a specific number?

When you say freeze do you mean the log stops exactly where it ends above and you get nothing else?

Please turn ping requests on if you haven't already done so.

**Comment by Akhilesh002** [comment]
The number of topics to which this client is subscribed exceeds 3000.
The log stops exactly where it ends above and I get nothing else. The Application UI also freezes (unresponsive) at that point.
 Ping requests are enabled. I didn't get logs of that too.

**Comment by shamblett** [comment]
OK so if this is happeniing 'The Application UI also freezes (unresponsive) at that point.' how do you know the package is causing this? It could just be general resource exhaustion, what platform are you running it on?

**Comment by shuaibakram** [comment]
The app works fine when this package is removed. 
Am running it on Android (havent tested on ios yet).

**Comment by Akhilesh002** [comment]
The Application works fine when this package is removed.
I'm running it on Android.

**Comment by shamblett** [comment]
If you remove the package(assuming by this you mean the client) how are you processing 3000+ subscriptions? Are you saying some other client is OK with this but this package isn't? Does whatever else you are doing run under flutter?  There's still nothing to say this is the fault of this package, you may have to profile your device.

**Comment by Akhilesh002** [comment]
I have an android app, which is running perfectly fine for 4000+ subscriptions.
I'm currently porting application to flutter.
The following steps confirmed the issue.
1. The issue was there when number of subscriptions were 3000+
2. I reduced number of subscriptions for the same user to 1000+ and issues were not there
I have repeated the above steps for some other users by giving access to some dummy topics. The issue was there.

**Comment by shamblett** [comment]
OK thanks I can see what you are doing a little better, but my question above still stands, without attaching observatory to the app how do you know its the fault of the package, it could be the flutter runtime is causing this, especially with the GUI freezing which the package can't affect at all. It looks like some resource starvation in the runtime, without knowing there's not much to do.

One question, does it do the same with logging off(or on), does it always bail at the same number of subscriptions.

Note I don't use flutter, I use the Dart VM so I don't have any experience with it.

**Comment by shamblett** [comment]
No further updates, closing.
