### ISSUE TITLE
When I prepare to connect, if the connection is not successful, an MqttNoConnectionException will be thrown every five seconds

### ISSUE THREAD

**Issue by maxfrees** [shamblett/mqtt5_client#105]
When I prepare to connect, if the connection is not successful, an MqttNoConnectionException will be thrown every five seconds.

Where is this five-second set from, and can it be configured by the user

**Comment by shamblett** [comment]
It comes from this line in MqttSynchronousServerConnectionHandler constructor -
```
 connectTimer = MqttCancellableAsyncSleep(5000);
```
This should only be raised 3 times (default, this is changeable)per any single connect() call.

This has been updated in mqtt_client and raised here as #106. Closing this. work will be carried out on #106 .
