### ISSUE TITLE
keepAlivePeriod changes are not backward compatible

### ISSUE THREAD

**Issue by Anshuman115** [shamblett/mqtt5_client#108]
Earlier setting up **keepAlive** only worked fine but now after updating to the latest version of the package, we need to specify both **keepAlive** and **keepAlivePeriod**, else it keeps on disconnecting.

Its kind of a breaking change for the existing users of the package.

**Comment by shamblett** [comment]
Not sure what you mean by 'setting up keepAlive'. You have always had to set the keepAlivePeriod from its default to enable keepalive, there is no separate keepAlive property. Running the mqtt_server_client example gives -
```
/development/google/dart/dart-sdk/bin/dart --enable-asserts --no-serve-devtools /development/google/dart/projects/mqtt5_client/example/mqtt5_server_client.dart
EXAMPLE::Mqtt5 client connecting....
EXAMPLE::OnConnected client callback - Client connection was successful
EXAMPLE::Mqtt5 server client connected, return code is success
EXAMPLE::Subscribing to the test/lol topic
EXAMPLE::Subscribing to the Dart/Mqtt5_client/testtopic topic
EXAMPLE::Sleeping....
EXAMPLE::Subscription confirmed for topic test/lol
EXAMPLE::Published notification:: topic is test/lol, with Qos MqttQos.atMostOnce
EXAMPLE::Change notification:: topic is <test/lol>, payload is <-- test 3 -->
EXAMPLE::Subscription confirmed for topic Dart/Mqtt5_client/testtopic
EXAMPLE::Publishing our topic now we are subscribed
EXAMPLE::Published notification:: topic is Dart/Mqtt5_client/testtopic, with Qos MqttQos.exactlyOnce
EXAMPLE::Change notification:: topic is <Dart/Mqtt5_client/testtopic>, payload is <-- Hello from mqtt5_client -->
EXAMPLE::Ping response client callback invoked
EXAMPLE::Ping response client callback invoked
EXAMPLE::Unsubscribing
EXAMPLE::Disconnecting
EXAMPLE::OnDisconnected client callback - Client disconnection
EXAMPLE::OnDisconnected callback is solicited, topic has been notified - this is correct

Process finished with exit code 0
```
There is no disconnection present in the log.

What exactly is your code doing?

**Comment by Anshuman115** [comment]
I've been using your MQTT package without issues until a recent update introduced a recurring problem: the client repeatedly disconnects with the log message "keep alive is disabled." I noticed this behavior change after the package was updated.

Here's the relevant part of my code:
```
late MqttServerClient client;

client = MqttServerClient(server, clientId);
client.port = port;
client.onConnected = _onConnected;
client.onDisconnected = _onDisconnected;
client.onSubscribed = _onSubscribed;
client.pongCallback = _pong;

final MqttConnectMessage connMess = MqttConnectMessage()
    .withClientIdentifier(clientId)
    .keepAliveFor(60)  // This sets the keepAlive to 60 seconds
    .startClean();

client.connectionMessage = connMess;

// Then client.connect ......

```

In my original implementation, I never explicitly set **client.keepAlivePeriod**. The method **keepAliveFor(60)** was intended to set the keepAlive period to 60 seconds. 
However, after your recent changes, I checked your commits and I found that there's a new conditional check where if **keepAlivePeriod > DefaultPeriod**, additional configurations are applied; otherwise, it logs **"keep alive is disabled."**

To resolve the issue, I added **client.keepAlivePeriod = 60** to my code, and it started working as expected. 

It seems that the recent changes might have unintentionally impacted the functionality related to setting the keepAlivePeriod.

**Comment by shamblett** [comment]
Your using server side keep alive, from the API docs for 'keepAlive' on the connect message -
```
/// Keep alive
  ///
  /// The Keep Alive is a time interval measured in seconds. It is the maximum
  /// time interval that is permitted to elapse between the point at which
  /// the client finishes transmitting one MQTT Control Packet and the
  /// point it starts sending the next. It is the responsibility of the client
  /// to ensure that the interval between MQTT Control Packets being sent does
  /// not exceed the Keep Alive value. If Keep Alive is non-zero and in the
  /// absence of sending any other MQTT Control Packets,
  /// the client MUST send a ping request.
  ///
  /// If the Keep Alive value is non-zero and the broker does not receive an MQTT
  /// Control Packet from the client within one and a half times the Keep Alive
  /// time period, it MUST close the network connection to the client
  /// as if the network had failed.
  ///
  /// A Keep Alive value of 0 has the effect of turning off the Keep Alive mechanism.
  /// If Keep Alive is 0 the client is not obliged to send MQTT Control Packets
  /// on any particular schedule.
  ///
  /// The broker may have other reasons to disconnect the client, for instance because
  /// it is shutting down. Setting Keep Alive does not guarantee that the
  /// client will remain connected.
  ///
  /// The actual value of the Keep Alive is application specific; typically, this is
  /// a few minutes. The maximum value of 65,535 is 18 hours 12 minutes and 15 seconds.
  ///
  /// Note that in the context of the client this is known as the server keep alive mechanism
  /// as opposed to the client keep alive mechanism controlled through the [MqttClient.keepAlivePeriod]
  /// field. If you wish to use the server keep alive mechanism then it is up to you to ensure you
  /// send control packets within the keep alive time period.
```

Therefore its up to you to send a control packet(any one will do e'g. publish) in this time period. The client code for client side keepalive was incorrect in this area. There is no relationship between client side keep alive and server side keep alive(there was before, this was wrong) the code is now correct in this area.

If this breaks your use case then so be it, note the minor version number was increased to indicate an API change had been made.

I'm not understanding why you would want to use this mechanism when you know you are not going to send a control packet in this period unless you enable client side keepalive. What use case do you need this for?

**Comment by Anshuman115** [comment]
Thank you for clarifying the distinctions between client-side and server-side keep alive mechanisms.

In previous versions of the library, my application functioned correctly without explicitly setting **keepAlivePeriod**, as long as **keepAlive** was set in the MqttConnectMessage. 
However, following the recent update, it became necessary to explicitly set both **keepAlive** and **keepAlivePeriod** to prevent the client from disconnecting. 
Once I made this adjustment, **everything started working fine again**.

This behaviour change could potentially impact other users who might be relying on the previous functionality. 
Could it be possible to update the documentation or the release notes to explicitly state that both **keepAlive** and **keepAlivePeriod** need to be set to enable the keep alive functionality effectively? 

This clarification could prevent connectivity issues for others upgrading to the latest version.

**Comment by shamblett** [comment]
Nothing more to say on this, closing.
