### ISSUE TITLE
mqtt5_clinet master have a error about :_TypeError (type '(MqttMessage) => bool' is not a subtype of type '((MqttMessage?) => bool)?' of 'callback')

### ISSUE THREAD

**Issue by tongweizj** [shamblett/mqtt5_client#11]
return await super.connect(username, password);

Exception has occurred.
_TypeError (type '(MqttMessage) => bool' is not a subtype of type '((MqttMessage?) => bool)?' of 'callback')

**Comment by shamblett** [comment]
the migration to null safety is not yet complete, you should not be using the master branch of the repo, only published package versions. see my comments on #8
