### ISSUE TITLE
MqttClient.resubscribe() ignores previously used subscription options and user properties

### ISSUE THREAD

**Issue by pogojotz** [shamblett/mqtt5_client#114]
Calling `resubscribe()` (`_resubscribe()` through autoreconnect) ignores subscription option used for the original subscription and uses default options instead, leading to an undesired state.

**Comment by shamblett** [comment]
Yes you are correct, this is an omission, thanks for the PR.

**Comment by shamblett** [comment]
Change incorporated. Package re released at version 4.5.1
