### ISSUE TITLE
Version 4.6 uses Path ^1.9.1 which conflicts with stable branch

### ISSUE THREAD

**Issue by rshillington** [shamblett/mqtt5_client#119]
> sdk depends on path 1.9.0 and mqtt5_client >=4.6.0 depends on path ^1.9.1

I think this is a similar issue to https://github.com/shamblett/mqtt5_client/issues/48.

**Comment by shamblett** [comment]
I don't downgrade anymore, from[ this issue ](https://github.com/shamblett/mqtt_client/issues/551) on mqtt_client -
```

Flutter will pin dependecies for avaoiding breaking changes until they are sure that new versions of the dependencies can compile without issues. Here are some details https://github.com/dart-lang/sdk/blob/main/docs/Flutter-Pinned-Packages.md

...you can always override this try to add meta 1.15.0 by adding the following block to your pubspec.yaml

dependency_overrides:
meta: ^1.15.0

and then you can use the latest version
```

In your case this will be 'path'. Majes sense, it allows package maintainers like me to not care what flutter is doing.
