### ISSUE TITLE
Flutter Web Error :Error: Unsupported operation: default SecurityContext getter

### ISSUE THREAD

**Issue by tongweizj** [shamblett/mqtt5_client#14]
Hi,

I got a error in Flutter Web in mqtt5_client!

May I have a help to solve this issue?
<img width="771" alt="截屏2021-09-14 下午10 37 40" src="https://user-images.githubusercontent.com/665012/133278325-6be772d5-cff0-462d-bcf5-94fec53a8cf2.png">

**Comment by shamblett** [comment]
If you are using Flutter Web you should be using mqtt_browser_client, not the server client. Secure sockets are not supported in the browser, you only have ws or wss websockets. Please read the documentation.
