### ISSUE TITLE
Browser WS Connection: auto reconnect is not handling null values

### ISSUE THREAD

**Issue by Felixduelmer** [shamblett/mqtt5_client#19]
In the browser ws connection, the auto-reconnect function is not handling null values.

If the onOpen function of the Browser WS Connection Websocket receives the correct data the completer finishes with a null value. This threw an error as the return function was non-nullable. 

In the Server WS Connection, this is handled correctly. 
Pull request is open: #18

**Comment by shamblett** [comment]
Thanks, package re published at version 3.1.3, please re test.
