### ISSUE TITLE
MessageExpiryInterval should be Four Byte Integer

### ISSUE THREAD

**Issue by sethloco** [shamblett/mqtt5_client#33]
Hello,

I'm pretty sure the *MessageExpiryInterval* in the CONNECT will-properties should be a `MqttFourByteIntegerProperty`.
https://github.com/shamblett/mqtt5_client/blob/master/lib/src/messages/connect/mqtt_will_properties.dart#L66

Here it a link to it in the spec:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901064

**Comment by shamblett** [comment]
Yes, correct well spotted, I'll fix this.

**Comment by sethloco** [comment]
Excellent...thank you

**Comment by shamblett** [comment]
Updated, package re released at version 3.3.1
