### ISSUE TITLE
flutter_test resolve dependency fail

### ISSUE THREAD

**Issue by ldemyanenko** [shamblett/mqtt5_client#4]
When I'm trying to get packages, an error appears

Because every version of flutter_test from SDK depends on typed_data 1.1.6 and app depends on typed_data ^1.2.0, flutter_test from SDK is forbidden.
So, because app depends on flutter_test any from SDK, version solving failed.
pub get failed (1; So, because app depends on flutter_test any from sdk, version solving failed.)

Looks like all latest stable Flutter releases depend on typed_data 1.1.6

**Comment by shamblett** [comment]
OK, I've downgraded typed_data to 1.1.6 for now and re published the package at version 1.1.1

**Comment by ldemyanenko** [comment]
I'm using 
  mqtt5_client: ^1.1.1

There is another issue:
Because every version of flutter_test from sdk depends on crypto 2.1.4 and every version of mqtt5_client depends on crypto ^2.1.5, flutter_test from sdk is incompatible with mqtt5_client.
So, because app depends on both mqtt5_client ^1.1.1 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because app depends on both mqtt5_client ^1.1.1 and flutter_test any from sdk, version solving failed.)

**Comment by shamblett** [comment]
OK, downgraded crypto to 2.1.4, re published the package at 1.2.0.
