### ISSUE TITLE
Deap loop in mqtt_property_container.dart, functionvoid readFrom(MqttByteBuffer stream);

### ISSUE THREAD

**Issue by Jayleee** [shamblett/mqtt5_client#45]
mqtt5_client-3.3.3/lib/src/messages/properties/mqtt_property_container.dart 
the function readFrom() contains a while-loop, when stream data went wrong, this loop will be a dead loop because of the (length != 0).
<img width="687" alt="image" src="https://user-images.githubusercontent.com/20172799/216976346-7c7f80a0-a029-456c-b540-d6af21ef802c.png">
here come for help, please 
If (length != 0) changes to (length > 0) could be better ?

**Comment by shamblett** [comment]
Yes Ok, updated, will be in the next release

**Comment by shamblett** [comment]
Incorporated into version 3.3.6 now released.
