### ISSUE TITLE
path and meta requirements not compatible with Flutter stable

### ISSUE THREAD

**Issue by devaronius** [shamblett/mqtt5_client#48]
hi @shamblett, in your latest version update we noticed that you require

path: '^1.8.3'
meta: '^1.9.0' 

But the latest version of Flutter 3.7.4 stable. Is running with path 1.8.2. And meta 1.8.0

I've looked into the changes of `path` and the only change here was 

> Support up to 16 arguments in join function and up to 15 arguments in absolute function.

This seems not like something required for this package.

For the meta package 1.9.0:

> `Introduce @reopen to annotate class or mixin declarations that can safely extend classes marked base, final or interface.
> Introduce @MustBeOverridden to annotate class or mixin members which must be overridden in all subclasses.
> Deprecate @alwaysThrows, which can be replaced by using a return type of 'Never'.`
> 

I don't think these changes are critical for the package.

Could you make an update that lowers the path version back 1.8.2 and meta to 1.8.0 so developers that run Flutter stable can also use the library. we are now forced to use a override in our yaml file.

**Comment by devaronius** [comment]
I already made a pull request for this change.

https://github.com/shamblett/mqtt5_client/pull/49

**Comment by shamblett** [comment]
Done, package re released at version 3.3.7, flutter is a real pain for this, you would have thought that by now the Google guys would have worked out how not to pin versions of flutter to specific package versions.
