### ISSUE TITLE
 Solace Broker immediately disconnects mqtt5 client

### ISSUE THREAD

**Issue by victorciumacext** [shamblett/mqtt5_client#55]
Hi,

I'm trying to use `Solace` (https://docs.solace.com/index.html) but for some reason connection is dropped immediately. 
(disconnect callback is called, with `MqttDisconnectionOrigin.unsolicited`)

Couldn't figure out what's the problem, as Mqttx works fine with Solace on mqtt5 protocol;

On the other hand, the mqtt-3.1.1 library works well with Solace service.

**Comment by shamblett** [comment]
You need to check your broker logs to see why the broker is refusing the connection.
