### ISSUE TITLE
Could not make the mqtt5_client connect to a EMQX server with WS

### ISSUE THREAD

**Issue by RickyMckay** [shamblett/mqtt5_client#58]
I was only experimenting with this for fun (Ex IT developer who became a manager now retired and keeping my brain active with dart)

I tried initially to connect to a free EMQX cloud instance but no joy so I downloaded Mosquitto onto my PC and this worked. So now I downloaded EMQX and ran on my PC and again no Joy.

Just messing around and looking at the other language examples I modified the connection string to add /mqtt at the end i.e. 'ws://RJMC-Work/' becomes 'ws://RJMC-Work/mqtt' and bang this works.

**Comment by shamblett** [comment]
Yes some broker endpoints are constructed like this, it should be stated somewhere by the provider what the endpoints/ports are for any particular broker instance. I've had a few issues with users not being able to connect to EMQX brokers over web sockets, I'll bear this in mind.

**Comment by RickyMckay** [comment]
Just an FYI
