### ISSUE TITLE
mqtt5_client 4.0.1 incompatible flutter_test

### ISSUE THREAD

**Issue by zf8848** [shamblett/mqtt5_client#62]
Flutter version 3.13.6 , mqtt5_client 4.0.1:
Because every version of flutter_test from sdk depends on meta 1.9.1 and mqtt5_client >=4.0.1 depends on meta ^1.10.0, flutter_test from sdk is incompatible with mqtt5_client >=4.0.1.

**Comment by shamblett** [comment]
Flutter is a pain for this, fixed, meta now at 1.9.1, package re published at version 4.0.2
