### ISSUE TITLE
[Feature Request] (re)add "disconnectOnNoResponsePeriod" property

### ISSUE THREAD

**Issue by sebisteiner** [shamblett/mqtt5_client#68]
Hi

Thank you for providing `mqtt_client` and `mqtt5_client` 😃 

We are migrating from `mqtt_client` and we were using the `disconnectOnNoResponsePeriod` property:
https://github.com/shamblett/mqtt_client/blob/4ba0ce894d5c90264e02a0e99017a023f0cafbf1/example/mqtt_server_client_keep_alive_disconnect.dart#L55

Is there any specific reason why you removed it? Or would it be possible to readd it?

**Comment by shamblett** [comment]
Well spotted, unfortunately  the vast majority of my MQTT fixes are on the mqtt_client so it has this functionality. What I should do is also apply the feature to the mqtt5_client but this often lagging . 

This is what has happened here, the feature has not been removed from the mqqt_5 client it has not yet been added.

Ill add this functionality to this client on this issue.

**Comment by shamblett** [comment]
Functionality now added, package re released at version 4.3.0
