### ISSUE TITLE
Getting message twice while listening to MqttPublishMessage stream.

### ISSUE THREAD

**Issue by aarjan** [shamblett/mqtt5_client#73]
I am listening to MqttPublishMessage stream for published message acknowledgement. 

But, i am getting the message two times. Is it before and after the message is published?

**Comment by shamblett** [comment]
You should only get a message when its completed its handshake according to the protocol, I'll look at this.

**Comment by shamblett** [comment]
I'll need a log of what what happens when you publish a Qos 1 message( I assume this is the Qos level you mean here).
