### ISSUE TITLE
MqttSubscriptionTopic().matches function throws exception upon different lengths of topics

### ISSUE THREAD

**Issue by ashu-pietech** [shamblett/mqtt5_client#77]
I found that MqttSubscriptionTopic().matches function is throwing error upon comparing two different topics. But the case is that base topic's length must be greater than the comparing topic's length then it throws this error:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..3: 4
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      MqttSubscriptionTopic.matches (package:mqtt5_client/src/mqtt_subscription_topic.dart:93:56)`

Steps to reproduce:

1. The raw topic passed inside the MqttSubscriptionTopic() must be of greater length if separated by "/" than the topic passed inside MqttPublicationTopic()
2. compare both using the MqttSubscriptionTopic("passed raw topic").matches function

I've fixed the above issue and I'll create a PR

**Comment by ashu-pietech** [comment]
created PR for the same issue #78

**Comment by shamblett** [comment]
Merged, package re published at version 4.2.0
