### ISSUE TITLE
Null Safety Updates

### ISSUE THREAD

**Issue by shamblett** [shamblett/mqtt5_client#8]

**Comment by shamblett** [comment]
Null safety updates on the null safety branch, needs unit testing before merge

**Comment by tongweizj** [comment]
Hi shamblett
how about Null Safety Updates？
Does it finished？
I have a project to use it!

Thanks

**Comment by shamblett** [comment]
I'm working on this at the moment, should release a new version in the next few days.

Unless you specifically need MQTT 5 protocol features you could use the [mqtt_client ](https://pub.dev/packages/mqtt_client/versions/9.0.0)package. This implements the MQTT 3 protocol and has updated to null safety.

**Comment by tongweizj** [comment]
Thanks a lot!
The company use the mqtt5 server.
So I will wait!
Thanks for your hard work

**Comment by shamblett** [comment]
Complete, package re published at version 3.0.0.
