### ISSUE TITLE
Hello, this client everything works fine except it will drop connect by server

### ISSUE THREAD

**Issue by lucasjinreal** [shamblett/mqtt5_client#82]
I not saying that this has something wrong client, but I don't why the server will drop after it connects,

and this happen only casually, most of time it's normal, which could be the reason caused this?

**Comment by shamblett** [comment]
The client doesn't 'drop' connections, it simply listens for events from the underlying Dart/flutter runtime and reacts to them. If it receives say an onDone event from the network it closes its connection. There are many reasons why this event could be generated, network issues, broker issues etc.  You could start by looking at your broker logs to see what it is doing when the connection is lost.

**Comment by lucasjinreal** [comment]
this is really hard to debug, since the broker has millions of messages and this only happen sometimes, can not make it happen every time.

and once it happens, it will keep connect -> disconnect -> connecting -> connected -> disconnected -> connecting.... forver repeat.

I though this shouldn't happen either.
