### ISSUE TITLE
Replace `dart:html` to `universal_html` for better universal support

### ISSUE THREAD

**Issue by deepanchal** [shamblett/mqtt5_client#85]
## Description

Currently, https://github.com/shamblett/mqtt_client uses https://pub.dev/packages/universal_html package which helps with importing `MqttBrowserClient` in app environments. It would be nice to have this feature in this library as well.

We can port over this change from `mqtt_client` to `mqtt5_client`. 
https://github.com/shamblett/mqtt_client/commit/d7eec87d5f151e09d006fab73a68346202d31719

**Comment by shamblett** [comment]
Package re published at version 4.2.1
