### ISSUE TITLE
Request/Response full support / Update README

### ISSUE THREAD

**Issue by Louis-PhilippeGentile** [shamblett/mqtt5_client#92]
Hello,

The README at the root of the project mentions that 
> Flow control and Request/Response functionality is not fully supported.

However, when sifting through the documentation, I failed to find anything relating to the Request/Response feature of MQTT 5 that is not supported by this package.

Am I missing something, or is the README out of date?

**Comment by shamblett** [comment]
I think you are right, the client does support request/response in the connect and connect ack messages, the received connect ack message is stored in the connection state so the response information is available to the user . I'll update the README.

**Comment by MichalNemec** [comment]
I would like to ask as well about request response. Does not seem that publish implements response topic.

could that be implemented since its supported in mqtt5?
https://www.emqx.com/en/blog/mqtt5-request-response

**Comment by Louis-PhilippeGentile** [comment]
> I would like to ask as well about request response. Does not seem that publish implements response topic.
> 
> could that be implemented since its supported in mqtt5? https://www.emqx.com/en/blog/mqtt5-request-response

I believe it is implemented, or at least it is present in the documentation as part of the [MqttPublishVariableHeader](https://pub.dev/documentation/mqtt5_client/latest/mqtt5_client/MqttPublishVariableHeader-class.html) class as the [responseTopic](https://pub.dev/documentation/mqtt5_client/latest/mqtt5_client/MqttPublishVariableHeader/responseTopic.html) property.

The MqttPublishMessage also contains a [method](https://pub.dev/documentation/mqtt5_client/latest/mqtt5_client/MqttPublishMessage/withResponseTopic.html) to directly set the responseTopic.

**Comment by MichalNemec** [comment]
Oh, i completely missed this, thank you for correcting me!

**Comment by alimcomp** [comment]
Hi and thanks
When you are going to fix readme file?

**Comment by shamblett** [comment]
Done, package re published at version 4.2.4
