### ISSUE TITLE
how to use MqttBrowserClient

### ISSUE THREAD

**Issue by xBLACKICEx** [shamblett/mqtt5_client#95]
how to connect mqtt server in browser ?

i can't connect to any mqtt  server like using wss hive.cloud or emqx.com with MqttBrowserClient

the mobile side works fine. for me with MqttServerClient client.secure and client.securityContext settings.

What am I doing wrong? What step am I missing on Browser version?

![图片](https://github.com/shamblett/mqtt5_client/assets/51036094/c1dda909-4e36-43db-b94d-18f0144fdf34)
![图片](https://github.com/shamblett/mqtt5_client/assets/51036094/042b51c7-c1d0-4f0b-a5c9-4b6477732aca)
![图片](https://github.com/shamblett/mqtt5_client/assets/51036094/5f7f8cdf-b956-479e-99df-cc5b0b408723)

**Comment by shamblett** [comment]
Try removing your websocket protocols setting, or setting it to []. Check your port is correct. 

Check your broker logs as to why its refusing the connection.

**Comment by xBLACKICEx** [comment]
i found the problem  need add **mqtt** at the end hostname, some thing like this:
```dart
MqttBrowserClient.witport(
"wss://xxx/mqtt",
"flutterclientid",
8884
)
```
